  schema: ["remote-schema.graphql", "schema.graphql"]
  documents: ["src/**/*.graphql"]
  extensions:
    endpoints:
      default: http://localhost:4000
  generates:
    ./src/types/generated-types.ts:
      plugins:
        - typescript
        - typescript-operations
